export const BlogPosts = [
  {
    type_of: 'article',
    id: 1133292,
    title: 'Linked List Simplified: Part 1',
    description:
      "If you've just started your programming journey or it's been a while one thing you've came across...",
    readable_publish_date: "Jul 6 '22",
    slug: 'linked-list-simplified-part-1-2ian',
    path: '/pb/linked-list-simplified-part-1-2ian',
    url: 'https://dev.to/pb/linked-list-simplified-part-1-2ian',
    comments_count: 0,
    public_reactions_count: 4,
    collection_id: null,
    published_timestamp: '2022-07-06T11:13:45Z',
    positive_reactions_count: 4,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--5yqMt4AV--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/9oiln0aobq0v4s7x23st.png',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--ADA7CfXQ--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/9oiln0aobq0v4s7x23st.png',
    canonical_url: 'https://dev.to/pb/linked-list-simplified-part-1-2ian',
    created_at: '2022-07-06T11:13:45Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2022-07-06T11:13:45Z',
    last_comment_at: '2022-07-06T11:13:45Z',
    reading_time_minutes: 4,
    tag_list: ['beginners', 'webdev', 'tutorial'],
    tags: 'beginners, webdev, tutorial',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 889859,
    title: 'Vim Shortcuts to get you started as a Beginner',
    description:
      'Disclaimer: This post includes just the bare minimum commands which you need to get started using...',
    readable_publish_date: "Jan 1 '22",
    slug: 'vim-shortcuts-to-get-you-started-as-a-beginner-4ga0',
    path: '/pb/vim-shortcuts-to-get-you-started-as-a-beginner-4ga0',
    url: 'https://dev.to/pb/vim-shortcuts-to-get-you-started-as-a-beginner-4ga0',
    comments_count: 1,
    public_reactions_count: 7,
    collection_id: null,
    published_timestamp: '2022-01-01T16:29:46Z',
    positive_reactions_count: 7,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--iaZdx1DT--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ev5rs405m8m0sqev8rzv.png',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--zV_UWRPU--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ev5rs405m8m0sqev8rzv.png',
    canonical_url:
      'https://dev.to/pb/vim-shortcuts-to-get-you-started-as-a-beginner-4ga0',
    created_at: '2021-11-06T04:47:45Z',
    edited_at: '2022-01-01T16:53:42Z',
    crossposted_at: null,
    published_at: '2022-01-01T16:29:46Z',
    last_comment_at: '2022-01-10T18:06:35Z',
    reading_time_minutes: 3,
    tag_list: ['beginners', 'programming', 'productivity', 'vim'],
    tags: 'beginners, programming, productivity, vim',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 839170,
    title: 'Open Source Programs for Students to participate',
    description:
      'Open Source Software is one of the most beautiful creations of humankind. It not only powers the...',
    readable_publish_date: "Sep 26 '21",
    slug: 'open-source-programs-for-students-to-participate-55gm',
    path: '/pb/open-source-programs-for-students-to-participate-55gm',
    url: 'https://dev.to/pb/open-source-programs-for-students-to-participate-55gm',
    comments_count: 4,
    public_reactions_count: 332,
    collection_id: null,
    published_timestamp: '2021-09-26T15:37:26Z',
    positive_reactions_count: 332,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--mFtzqMaY--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/egxj3txtl1sp71806fuu.jpg',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--6VZiMdwk--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/egxj3txtl1sp71806fuu.jpg',
    canonical_url:
      'https://dev.to/pb/open-source-programs-for-students-to-participate-55gm',
    created_at: '2021-09-24T15:20:22Z',
    edited_at: '2021-09-28T18:09:29Z',
    crossposted_at: null,
    published_at: '2021-09-26T15:37:26Z',
    last_comment_at: '2021-09-30T08:49:24Z',
    reading_time_minutes: 4,
    tag_list: ['beginners', 'opensource', 'webdev', 'codenewbie'],
    tags: 'beginners, opensource, webdev, codenewbie',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 823908,
    title: '1. Introduction to ReactJS and Why we should use it',
    description:
      'First of all thanks everyone for showing your support and subscribing to the series. I appreciate you...',
    readable_publish_date: "Sep 15 '21",
    slug: '1-introduction-to-reactjs-and-why-we-should-use-it-5e8a',
    path: '/pb/1-introduction-to-reactjs-and-why-we-should-use-it-5e8a',
    url: 'https://dev.to/pb/1-introduction-to-reactjs-and-why-we-should-use-it-5e8a',
    comments_count: 0,
    public_reactions_count: 40,
    collection_id: null,
    published_timestamp: '2021-09-15T06:26:52Z',
    positive_reactions_count: 40,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--MqmSGk-Q--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/tcch3dnqplgoup0emx1k.png',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--9W27Jpvx--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/tcch3dnqplgoup0emx1k.png',
    canonical_url:
      'https://dev.to/pb/1-introduction-to-reactjs-and-why-we-should-use-it-5e8a',
    created_at: '2021-09-14T18:16:31Z',
    edited_at: '2021-09-15T06:29:30Z',
    crossposted_at: null,
    published_at: '2021-09-15T06:26:52Z',
    last_comment_at: '2021-09-15T06:26:52Z',
    reading_time_minutes: 3,
    tag_list: ['beginners', 'webdev', 'javascript', 'react'],
    tags: 'beginners, webdev, javascript, react',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 819518,
    title: 'REACTIFIED: Learn ReactJS the simple way',
    description:
      "If you're a person who prefers reading over watching videos for learning new skills and technologies...",
    readable_publish_date: "Sep 10 '21",
    slug: 'reactified-learn-reactjs-the-simple-way-a2o',
    path: '/pb/reactified-learn-reactjs-the-simple-way-a2o',
    url: 'https://dev.to/pb/reactified-learn-reactjs-the-simple-way-a2o',
    comments_count: 1,
    public_reactions_count: 163,
    collection_id: null,
    published_timestamp: '2021-09-10T08:18:39Z',
    positive_reactions_count: 163,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--geLbHcP---/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/mz43skhq7yr98l311k7s.png',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--LzyqUbMy--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/mz43skhq7yr98l311k7s.png',
    canonical_url:
      'https://dev.to/pb/reactified-learn-reactjs-the-simple-way-a2o',
    created_at: '2021-09-10T07:54:35Z',
    edited_at: '2021-09-10T08:24:20Z',
    crossposted_at: null,
    published_at: '2021-09-10T08:18:39Z',
    last_comment_at: '2021-09-12T20:57:26Z',
    reading_time_minutes: 1,
    tag_list: ['beginners', 'javascript', 'webdev', 'react'],
    tags: 'beginners, javascript, webdev, react',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 754455,
    title: '10 GitHub repositories to become a better JavaScript Developer',
    description:
      'With the introduction of libraries and Frameworks like ReactJS, VueJS, Angular, SvelteJS and much...',
    readable_publish_date: "Jul 9 '21",
    slug: '10-github-repositories-which-will-help-you-to-become-a-better-javascript-developer-5om',
    path: '/pb/10-github-repositories-which-will-help-you-to-become-a-better-javascript-developer-5om',
    url: 'https://dev.to/pb/10-github-repositories-which-will-help-you-to-become-a-better-javascript-developer-5om',
    comments_count: 30,
    public_reactions_count: 2384,
    collection_id: null,
    published_timestamp: '2021-07-09T07:56:34Z',
    positive_reactions_count: 2384,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s---LOnr6xq--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/48lpp1nudqikcftmu06i.png',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--zJH8B3Tg--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/48lpp1nudqikcftmu06i.png',
    canonical_url:
      'https://dev.to/pb/10-github-repositories-which-will-help-you-to-become-a-better-javascript-developer-5om',
    created_at: '2021-07-09T07:56:34Z',
    edited_at: '2021-07-19T13:55:31Z',
    crossposted_at: null,
    published_at: '2021-07-09T07:56:34Z',
    last_comment_at: '2023-01-10T16:42:24Z',
    reading_time_minutes: 4,
    tag_list: ['javascript', 'productivity', 'beginners', 'github'],
    tags: 'javascript, productivity, beginners, github',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 751035,
    title: 'Introducing GoldFish : The minimalist Theme',
    description:
      'I would like to thanks for all of you for the immense support you gave to the JellyFish Theme. As it...',
    readable_publish_date: "Jul 6 '21",
    slug: 'introducing-goldfish-the-minimalist-theme-57km',
    path: '/pb/introducing-goldfish-the-minimalist-theme-57km',
    url: 'https://dev.to/pb/introducing-goldfish-the-minimalist-theme-57km',
    comments_count: 0,
    public_reactions_count: 4,
    collection_id: null,
    published_timestamp: '2021-07-06T14:25:48Z',
    positive_reactions_count: 4,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--Qv1t_zsU--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/xp0mepu7wh8lzz3gb7zn.png',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--of7YO7mz--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/xp0mepu7wh8lzz3gb7zn.png',
    canonical_url:
      'https://dev.to/pb/introducing-goldfish-the-minimalist-theme-57km',
    created_at: '2021-07-06T07:11:28Z',
    edited_at: '2021-07-06T14:35:41Z',
    crossposted_at: null,
    published_at: '2021-07-06T14:25:48Z',
    last_comment_at: '2021-07-06T14:25:48Z',
    reading_time_minutes: 1,
    tag_list: ['javascript', 'webdev', 'programming', 'vscode'],
    tags: 'javascript, webdev, programming, vscode',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 713572,
    title: 'Git Squash Simplified',
    description:
      'If you have just started as an open source contributor or planning to become one, you might came...',
    readable_publish_date: "Jul 2 '21",
    slug: 'git-squash-simplified-3ba1',
    path: '/pb/git-squash-simplified-3ba1',
    url: 'https://dev.to/pb/git-squash-simplified-3ba1',
    comments_count: 10,
    public_reactions_count: 213,
    collection_id: null,
    published_timestamp: '2021-07-02T06:19:54Z',
    positive_reactions_count: 213,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--m4rDDmqn--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ge5okltlvxtxyx1g8riu.PNG',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--qpu6B6r6--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ge5okltlvxtxyx1g8riu.PNG',
    canonical_url: 'https://dev.to/pb/git-squash-simplified-3ba1',
    created_at: '2021-05-31T10:41:10Z',
    edited_at: '2021-07-02T09:50:02Z',
    crossposted_at: null,
    published_at: '2021-07-02T06:19:54Z',
    last_comment_at: '2022-12-06T20:07:37Z',
    reading_time_minutes: 4,
    tag_list: ['productivity', 'javascript', 'webdev', 'git'],
    tags: 'productivity, javascript, webdev, git',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 713041,
    title: 'Introducing JellyFish - Theme your vscode will love',
    description:
      'From the day one of using visual studio code I always had a thought of designing my own theme one day...',
    readable_publish_date: "May 30 '21",
    slug: 'introducing-jellyfish-theme-your-vscode-will-love-22jm',
    path: '/pb/introducing-jellyfish-theme-your-vscode-will-love-22jm',
    url: 'https://dev.to/pb/introducing-jellyfish-theme-your-vscode-will-love-22jm',
    comments_count: 6,
    public_reactions_count: 35,
    collection_id: null,
    published_timestamp: '2021-05-30T18:14:47Z',
    positive_reactions_count: 35,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--ldS6Svfx--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/p3g31ipdkkrq0lussjsj.PNG',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--okR_jOU4--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/p3g31ipdkkrq0lussjsj.PNG',
    canonical_url:
      'https://dev.to/pb/introducing-jellyfish-theme-your-vscode-will-love-22jm',
    created_at: '2021-05-30T18:14:47Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2021-05-30T18:14:47Z',
    last_comment_at: '2021-06-06T07:50:18Z',
    reading_time_minutes: 2,
    tag_list: ['javascript', 'programming', 'webdev', 'vscode'],
    tags: 'javascript, programming, webdev, vscode',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
  {
    type_of: 'article',
    id: 675533,
    title: '10 GitHub Repositories every Developer should know',
    description:
      'Other than being the home for some of the most interesting Open Source Projects on the internet, GitH...',
    readable_publish_date: "Apr 23 '21",
    slug: '10-github-repositories-every-developer-should-know-ngm',
    path: '/pb/10-github-repositories-every-developer-should-know-ngm',
    url: 'https://dev.to/pb/10-github-repositories-every-developer-should-know-ngm',
    comments_count: 72,
    public_reactions_count: 3761,
    collection_id: null,
    published_timestamp: '2021-04-23T13:11:37Z',
    positive_reactions_count: 3761,
    cover_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--rIMJB0Lh--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/881jdm7sdnril6hn3f3l.PNG',
    social_image:
      'https://res.cloudinary.com/practicaldev/image/fetch/s--stD8Ib7T--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/881jdm7sdnril6hn3f3l.PNG',
    canonical_url:
      'https://dev.to/pb/10-github-repositories-every-developer-should-know-ngm',
    created_at: '2021-04-22T19:37:18Z',
    edited_at: '2021-04-25T10:34:25Z',
    crossposted_at: null,
    published_at: '2021-04-23T13:11:37Z',
    last_comment_at: '2022-03-17T16:34:07Z',
    reading_time_minutes: 4,
    tag_list: ['beginners', 'productivity', 'webdev', 'javascript'],
    tags: 'beginners, productivity, webdev, javascript',
    user: {
      name: 'Pawel',
      username: 'pb',
      twitter_username: 'pawelsb',
      github_username: 'pawelborkar',
      user_id: 618537,
      website_url: 'https://pawel.in',
      profile_image:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--tlcdpPUN--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
      profile_image_90:
        'https://res.cloudinary.com/practicaldev/image/fetch/s--zYp6OJGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/618537/3cd782cd-1a3a-4926-9eb6-1e55fba23a61.jpg',
    },
  },
];
